### PR TITLE
Bring Betterment/plaid-java up to date with Plaid/plaid-java

### PR DESCRIPTION
**Pull request by superwomyn**
https://trello.com/c/U9YaXI23/2752-2-upgrade-plaid-java-and-ruby-clients-to-support-tls-1-1

/domain @ceslami @reustmd @adamlangsner 
/platform @ceslami @reustmd @adamlangsner

### CODE REVIEW

**Comment by reustmd** [comment]
<< platformlgtm

**Comment by superwomyn** [comment]
bump @ceslami

**Comment by superwomyn** [comment]
bump @adamlangsner @ceslami @reustmd - would love to get this moving!

**Comment by adamlangsner** [comment]
this looks good to me, but there are some merge conflicts. so I'm hesitant to give it a real lgtm until those are resolved

**Comment by adamlangsner** [comment]
<< domain

**Comment by ceslami** [comment]
@superwomyn given the way we set up this merge, its going to be hard to resolve the merge conflicts on your local. we can take a few minutes tomorrow to fast forward a separate branch to mirror their master, resolve conflicts, and open a new PR. thanks for biting this off!

**Comment by superwomyn** [comment]
@ceslami ok. come find me when you have a few minutes to spare on a newb such as myself. thanks!

**Pull request closed without merging**
